name: wiroai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  intl: ^0.18.0
  args: ^2.4.0
  audioplayers: ^0.20.1
  video_player: ^2.5.1
  image: ^3.0.1
  ffmpeg_kit_flutter: ^4.5.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png